// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frxconirbzymjrwegygf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyeGNvbmlyYnp5bWpyd2VneWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MzkyMDAsImV4cCI6MjA3MDUxNTIwMH0.pWI6BSPh11EeHaCFz81I2Djp9PcNUbhCB4pUk2GtqPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});